ARG VERSION=1.0
ARG CUDA_VERSION=10.0
ARG UBUNTU_VERSION=18.04

FROM nvidia/cuda:10.0-devel-ubuntu18.04

LABEL maintainer="UASIS Projesi - Erol Kahraman"

ENV LANG en_US.UTF-8
ENV CUDA_VERSION $CUDA_VERSION


# Prerequisite for CUDA

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get upgrade -y --allow-unauthenticated
